# go-cqhttp正向ws
host: 'ws://127.0.0.1:8700'

# 学期开始日期
course_start: 2023-02-13

# 发送到目标
send_target:
#  - group_id: 群号
#  - user_id: qq账号

# 课前多少分钟发送
send_before: 20

# 课表时间
timetable:
  - - 8:00
    - 8:45

  - - 8:55
    - 9:40

  - - 10:10
    - 10:55

  - - 11:05
    - 11:50

  - - 14:00
    - 14:45

  - - 14:55
    - 15:40

  - - 16:00
    - 16:45

  - - 16:55
    - 17:40

  - - 19:00
    - 19:45

  - - 19:55
    - 20:40